"""Small server-rendered translation catalogue for the player portal."""

LANGUAGES = {'de': 'Deutsch', 'en': 'English'}

TEXT = {
    'de': {
        'portal_title': 'Das Kartell · Spielerportal', 'meta_description': 'Das Kartell · WarDogs Server, Leaderboard und deine persönlichen Spielerstatistiken.',
        'skip': 'Zum Inhalt', 'home_aria': 'Das Kartell – Startseite', 'login': 'Mit Steam anmelden', 'logout': 'Abmelden', 'language': 'Sprache',
        'nav_status': 'Serverstatus', 'nav_leaderboard': 'Leaderboard', 'nav_profile': 'Mein Profil', 'nav_quests': 'Quests', 'nav_rewards': 'Belohnungen', 'footer_tagline': 'Mehr als nur ein Spiel.', 'footer_portal': 'WarDogs · Community-Portal',
        'home_title': 'Das nächste Match<br>wartet auf dich.', 'to_leaderboard': 'Zum Leaderboard', 'players_online': 'Spieler gerade online', 'servers_current': 'von 3 Servern mit aktuellen Daten', 'retry': 'Erneut laden', 'servers': 'Unsere Server', 'refresh_30': 'Aktualisiert sich alle 30 Sekunden',
        'map_mode': 'Karte / Modus', 'round_ended': 'Runde beendet', 'score': 'Punktestand', 'no_score': 'Noch kein Punktestand', 'players': 'Spieler', 'players_last': 'Spieler · zuletzt', 'not_recorded': 'Noch nicht erfasst', 'status_online': 'Online', 'status_last': 'Letzte bekannte Daten', 'status_none': 'Keine Messung', 'no_data': 'Noch keine Daten', 'unknown': 'Unbekannt',
        'leader_title': 'Wer führt das Feld an?', 'leader_copy': 'Die Rangliste unserer Server. Sortiere nach K/D oder erspieltem Cash.', 'server': 'Server', 'period': 'Zeitraum', 'sort_by': 'Sortieren nach', 'show': 'Anzeigen', 'page': 'Seite', 'up_to_50': 'Bis zu 50 Spieler', 'rank': 'Rang', 'player': 'Spieler', 'kills': 'Kills', 'deaths': 'Tode', 'cash': 'Cash · USD', 'no_entries': 'Noch keine Einträge', 'no_entries_copy': 'Für diese Auswahl wurden noch keine gewerteten Spielerwerte erfasst. Versuche einen anderen Zeitraum oder Server.', 'view_status': 'Serverstatus ansehen', 'ranking_pages': 'Ranglisten-Seiten', 'back': '← Zurück', 'next': 'Weiter →', 'leader_note': '7 und 30 Tage umfassen den heutigen UTC-Kalendertag. Für die K/D-Rangliste brauchst du mindestens 5 Tode und 30 Minuten Spielzeit auf diesem Server.',
        'profile_title': 'Mein Profil', 'avatar_alt': 'Dein Steam-Avatar', 'private': 'Nur für dich sichtbar', 'first_match': 'Dein erstes Match fehlt noch.', 'first_match_copy': 'Für deine Steam-ID sind noch keine Spielerdaten gespeichert. Nach deinem nächsten Besuch auf unseren Servern erscheinen sie hier.', 'view_servers': 'Server ansehen', 'playtime_total': 'Spielzeit gesamt', 'quest_progress': 'Dein Fortschritt', 'quest_points': 'Quest-Punkte', 'view_quests': 'Quests ansehen', 'known_names': 'Bekannte Namen', 'server_balance': 'Deine Server-Bilanz', 'berlin_time': 'Zeiten in Europe/Berlin', 'last_seen': 'Zuletzt gesehen:', 'playtime': 'Spielzeit', 'average_ping': 'Durchschnittlicher Ping', 'statistics': 'Statistiken', 'total': 'Gesamt', 'days_7': '7 Tage', 'days_30': '30 Tage', 'last_round': 'Zuletzt erfasste Runde', 'faction_entries': 'Fraktionsbeitritte', 'entries_detected': 'erkannte Beitritte', 'no_faction_entries': 'Noch keine Fraktionsbeitritte erfasst.', 'no_server_stats': 'Auf diesem Server sind noch keine Stats für dich gespeichert.', 'ban_history': 'Deine Ban-Historie', 'entries_private': 'Einträge · privat', 'active': 'Aktiv', 'expired': 'Abgelaufen', 'revoked': 'Aufgehoben', 'duration': 'Dauer', 'expires': 'Ablaufdatum', 'permanent': 'Unbefristet', 'no_bans': 'Keine Bans gespeichert', 'no_bans_copy': 'Für deine Steam-ID gibt es keine Einträge in der Ban-Historie.',
        'quests_title': 'Quests', 'your_quests': 'Deine Quests', 'quests_copy': 'Verdiene Punkte durch aktive Spielzeit in einem echten Team, Cash und wöchentliche Fraktionsziele.', 'your_score': 'Dein Punktestand', 'permanent_quest': 'Dauerhafte Quest', 'active_playtime': 'Aktive Spielzeit', 'active_playtime_copy': '1 Punkt je volle Stunde in einer echten Fraktion während einer laufenden Runde.', 'cash_earned': 'Verdientes Cash', 'cash_earned_copy': '1 Punkt je volle 100.000 USD verdientes Cash.', 'until_next_point': 'Noch {value} bis zum nächsten Punkt.', 'faction_playtime': 'Fraktion Playtime', 'reset_monday': 'Reset montags, 00:00 Uhr', 'this_week': 'in dieser Woche', 'hours_2': '2 Std. · +5 Punkte', 'hours_4': '4 Std. · +5 Punkte', 'recent_points': 'Letzte Punktbewegungen', 'timestamp': 'Zeitpunkt', 'source': 'Quelle', 'no_point_history': 'Noch keine Punktebewegungen gespeichert.', 'legacy_playtime': 'Übernommene Spielzeit', 'eligible_playtime': 'Aktive Spielzeit', 'cash_source': 'Verdientes Cash', 'weekly_team': 'Wochenquest', 'admin_set': 'Administratives Update',
        'rewards_title': 'Belohnungen', 'rewards_heading': 'Punkte einlösen', 'rewards_copy': 'Einlösungen werden vom Bot geprüft. Für einen Fraktionswechsel werden Punkte vor der sicheren Ausführung reserviert.', 'faction_change': 'Fraktionswechsel', 'faction_change_copy': 'Wechsle sofort auf einem Server in eine echte Fraktion.', 'faction_warning': 'Der Fraktionswechsel setzt dein aktuelles Loadout zurück.', 'target_faction': 'Ziel-Fraktion', 'redeem_for': 'Für {points} Punkte einlösen', 'vip': 'VIP', 'vip_copy': 'VIP wird nach der Einlösung durch das Admin-Team auf dem gewählten Server aktiviert.', 'one_week': '1 Woche', 'one_month': '1 Monat', 'vip_status': 'Dein VIP-Status', 'free': 'Frei', 'pending_activation': 'Wartet auf Aktivierung', 'active_vip': 'Aktiv', 'removal_pending': 'Abgelaufen – Entfernung ausstehend', 'removed_vip': 'Entfernt', 'expires_in': 'Läuft ab:', 'shop_requests': 'Deine letzten Einlösungen', 'request_faction': 'Fraktionswechsel', 'request_vip': 'VIP', 'request_pending': 'Wird geprüft', 'request_processing': 'Wird ausgeführt', 'request_charged': 'Punkte reserviert', 'request_executing': 'Wird sicher ausgeführt', 'request_reconciliation_required': 'Manuelle Prüfung erforderlich', 'request_success': 'Erfolgreich', 'request_rejected': 'Abgelehnt', 'request_failed': 'Fehlgeschlagen', 'no_shop_requests': 'Noch keine Einlösungen.', 'slots_note': 'VIP-Plätze werden pro Server durch das Admin-Team geprüft. Ein offener oder abgelaufener VIP bleibt reserviert, bis er extern bestätigt entfernt wurde.',
        'error_busy_title': 'Anmeldung ausgelastet', 'error_busy': 'Bitte warte einen Moment und starte die Anmeldung erneut.', 'error_login_title': 'Anmeldung nicht abgeschlossen', 'error_login': 'Die Steam-Anmeldung wurde abgebrochen, ist abgelaufen oder konnte nicht bestätigt werden. Bitte melde dich erneut an.', 'error_db_title': 'Daten kurzzeitig nicht verfügbar', 'error_db': 'Die Serverdaten sind gerade nicht erreichbar. Bitte versuche es in Kürze erneut.', 'error_filter_title': 'Ungültige Auswahl', 'error_filter': 'Bitte wähle Server, Zeitraum und Sortierung über die Filter im Leaderboard.', 'error_page_title': 'Seite nicht verfügbar', 'error_page': 'Diese Seite wurde nicht gefunden oder der Zugriff ist nicht erlaubt.', 'home': 'Zur Startseite', 'updated': 'Stand:',
    },
    'en': {
        'portal_title': 'Das Kartell · Player Portal', 'meta_description': 'Das Kartell · WarDogs servers, leaderboard and your personal player statistics.',
        'skip': 'Skip to content', 'home_aria': 'Das Kartell – home', 'login': 'Sign in with Steam', 'logout': 'Sign out', 'language': 'Language',
        'nav_status': 'Server status', 'nav_leaderboard': 'Leaderboard', 'nav_profile': 'My profile', 'nav_quests': 'Quests', 'nav_rewards': 'Rewards', 'footer_tagline': 'More than just a game.', 'footer_portal': 'WarDogs · Community portal',
        'home_title': 'The next match<br>is waiting for you.', 'to_leaderboard': 'View leaderboard', 'players_online': 'Players online now', 'servers_current': 'of 3 servers with current data', 'retry': 'Try again', 'servers': 'Our servers', 'refresh_30': 'Updates every 30 seconds',
        'map_mode': 'Map / mode', 'round_ended': 'Round ended', 'score': 'Score', 'no_score': 'No score yet', 'players': 'Players', 'players_last': 'Players · last known', 'not_recorded': 'Not recorded yet', 'status_online': 'Online', 'status_last': 'Last known data', 'status_none': 'No measurement', 'no_data': 'No data yet', 'unknown': 'Unknown',
        'leader_title': 'Who leads the field?', 'leader_copy': 'The rankings for our servers. Sort by K/D or earned cash.', 'server': 'Server', 'period': 'Period', 'sort_by': 'Sort by', 'show': 'Show', 'page': 'Page', 'up_to_50': 'Up to 50 players', 'rank': 'Rank', 'player': 'Player', 'kills': 'Kills', 'deaths': 'Deaths', 'cash': 'Cash · USD', 'no_entries': 'No entries yet', 'no_entries_copy': 'No scored player data has been recorded for this selection yet. Try another period or server.', 'view_status': 'View server status', 'ranking_pages': 'Leaderboard pages', 'back': '← Back', 'next': 'Next →', 'leader_note': '7 and 30 days include the current UTC calendar day. K/D ranking requires at least 5 deaths and 30 minutes of playtime on that server.',
        'profile_title': 'My profile', 'avatar_alt': 'Your Steam avatar', 'private': 'Visible only to you', 'first_match': 'Your first match is still missing.', 'first_match_copy': 'No player data has been saved for your Steam ID yet. It will appear here after your next visit to our servers.', 'view_servers': 'View servers', 'playtime_total': 'Total playtime', 'quest_progress': 'Your progress', 'quest_points': 'Quest points', 'view_quests': 'View quests', 'known_names': 'Known names', 'server_balance': 'Your server record', 'berlin_time': 'Times in Europe/Berlin', 'last_seen': 'Last seen:', 'playtime': 'Playtime', 'average_ping': 'Average ping', 'statistics': 'Statistics', 'total': 'All time', 'days_7': '7 days', 'days_30': '30 days', 'last_round': 'Last recorded round', 'faction_entries': 'Faction joins', 'entries_detected': 'detected joins', 'no_faction_entries': 'No faction joins recorded yet.', 'no_server_stats': 'No stats have been saved for you on this server yet.', 'ban_history': 'Your ban history', 'entries_private': 'entries · private', 'active': 'Active', 'expired': 'Expired', 'revoked': 'Revoked', 'duration': 'Duration', 'expires': 'Expires', 'permanent': 'Permanent', 'no_bans': 'No bans saved', 'no_bans_copy': 'There are no entries for your Steam ID in the ban history.',
        'quests_title': 'Quests', 'your_quests': 'Your quests', 'quests_copy': 'Earn points through active playtime in a real team, cash and weekly faction goals.', 'your_score': 'Your score', 'permanent_quest': 'Permanent quest', 'active_playtime': 'Active playtime', 'active_playtime_copy': '1 point for every full hour in a real faction during an active round.', 'cash_earned': 'Cash earned', 'cash_earned_copy': '1 point for every 100,000 USD earned.', 'until_next_point': '{value} until the next point.', 'faction_playtime': 'Faction playtime', 'reset_monday': 'Resets Mondays, 00:00', 'this_week': 'this week', 'hours_2': '2 hrs · +5 points', 'hours_4': '4 hrs · +5 points', 'recent_points': 'Recent point activity', 'timestamp': 'Timestamp', 'source': 'Source', 'no_point_history': 'No point activity saved yet.', 'legacy_playtime': 'Imported playtime', 'eligible_playtime': 'Active playtime', 'cash_source': 'Cash earned', 'weekly_team': 'Weekly quest', 'admin_set': 'Administrative update',
        'rewards_title': 'Rewards', 'rewards_heading': 'Redeem points', 'rewards_copy': 'Redemptions are checked by the bot. Points for a faction change are reserved before safe execution.', 'faction_change': 'Faction change', 'faction_change_copy': 'Change immediately into a real faction on one server.', 'faction_warning': 'Changing faction resets your current loadout.', 'target_faction': 'Target faction', 'redeem_for': 'Redeem for {points} points', 'vip': 'VIP', 'vip_copy': 'After redemption, the admin team activates VIP on the selected server.', 'one_week': '1 week', 'one_month': '1 month', 'vip_status': 'Your VIP status', 'free': 'Free', 'pending_activation': 'Awaiting activation', 'active_vip': 'Active', 'removal_pending': 'Expired – removal pending', 'removed_vip': 'Removed', 'expires_in': 'Expires:', 'shop_requests': 'Your recent redemptions', 'request_faction': 'Faction change', 'request_vip': 'VIP', 'request_pending': 'Being checked', 'request_processing': 'Being processed', 'request_charged': 'Points reserved', 'request_executing': 'Executing safely', 'request_reconciliation_required': 'Manual review required', 'request_success': 'Successful', 'request_rejected': 'Rejected', 'request_failed': 'Failed', 'no_shop_requests': 'No redemptions yet.', 'slots_note': 'VIP slots are checked per server by the admin team. A pending or expired VIP remains reserved until its external removal is confirmed.',
        'error_busy_title': 'Sign-in is busy', 'error_busy': 'Please wait a moment and start sign-in again.', 'error_login_title': 'Sign-in was not completed', 'error_login': 'The Steam sign-in was cancelled, expired or could not be verified. Please sign in again.', 'error_db_title': 'Data temporarily unavailable', 'error_db': 'Your data could not be loaded right now. Please try again shortly.', 'error_filter_title': 'Invalid selection', 'error_filter': 'Choose server, period and sorting using the leaderboard filters.', 'error_page_title': 'Page unavailable', 'error_page': 'This page was not found or access is not allowed.', 'home': 'Go to home', 'updated': 'Updated:',
    },
}

# Kept separately so the main concise catalogue remains easy to scan.
TEXT['de'].update({
    'redeem': 'Einlösen', 'vip_slots': 'VIP-Plätze belegt',
    'current_server': 'Aktueller Server:', 'not_on_server': 'Du bist auf keinem aktuellen Server erkannt.',
    'reward_ready': 'Einlösung möglich', 'not_enough_points': 'Nicht genügend Quest-Punkte.',
    'not_online': 'Du musst auf einem Server online sein.',
    'same_faction': 'Du bist bereits in dieser Fraktion.',
    'balance_limit': 'Nicht möglich: Die Team-Balance würde mehr als vier Spieler abweichen.',
    'no_vip_slots': 'Auf diesem Server sind keine VIP-Plätze frei.',
    'vip_exists': 'Du hast auf diesem Server bereits einen reservierten oder aktiven VIP.',
})
TEXT['en'].update({
    'redeem': 'Redeem', 'vip_slots': 'VIP slots occupied',
    'current_server': 'Current server:', 'not_on_server': 'You are not detected on a current server.',
    'reward_ready': 'Redemption available', 'not_enough_points': 'Not enough quest points.',
    'not_online': 'You must be online on a server.',
    'same_faction': 'You are already in this faction.',
    'balance_limit': 'Not available: team balance would differ by more than four players.',
    'no_vip_slots': 'There are no VIP slots available on this server.',
    'vip_exists': 'You already have a reserved or active VIP on this server.',
})


def translate(language: str, key: str, **values) -> str:
    text = TEXT.get(language, TEXT['de']).get(key, TEXT['de'].get(key, key))
    return text.format(**values)
